name: simple_messenger
description: A flutter project using Clean arch.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.1.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # core
  flutter_modular: ^6.3.2
  intl: ^0.18.1
  dartz: ^0.10.1
  path_provider: ^2.1.1
  permission_handler: ^11.0.1
  dio: ^5.3.3
  pretty_dio_logger: ^1.3.1
  flutter_local_notifications: ^16.1.0

  # Localization [optional]
  easy_localization: ^3.0.3

  # Firebase
  firebase_core: ^2.21.0
  firebase_crashlytics: ^3.4.2
  firebase_messaging: ^14.7.2

  # Socket
  socket_io_client: ^2.0.3+1

  # General
  url_launcher: ^6.2.1
  package_info_plus: ^4.2.0

  # State Management
  bloc: ^8.1.2
  equatable: ^2.0.5
  flutter_bloc: ^8.1.3

  # Storage
  shared_preferences: ^2.2.2
  flutter_secure_storage: ^9.0.0

  # UI / Forms
  line_icons: ^2.0.3
  cached_network_image: ^3.3.0
  flutter_svg: ^2.0.8
  all_validations_br: ^3.0.0
  fluttertoast: ^8.2.2
  mask_text_input_formatter: ^2.5.0
  validatorless: ^1.2.3

  # UI - Optinal
  loading_animation_widget: ^1.2.0+4    # relate to loader mixin
  awesome_snackbar_content: ^0.1.3      # related to messages mixin

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/vectors/
    - assets/translations/

  fonts:
   - family: Poppins
     fonts:
       - asset: assets/fonts/Poppins-Black.ttf
       - asset: assets/fonts/Poppins-Bold.ttf
       - asset: assets/fonts/Poppins-Light.ttf
       - asset: assets/fonts/Poppins-Medium.ttf
       - asset: assets/fonts/Poppins-Regular.ttf
       - asset: assets/fonts/Poppins-SemiBold.ttf
